// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apiweb.Data;

#nullable disable

namespace apiweb.Migrations
{
    [DbContext(typeof(UsuarioContext))]
    [Migration("20260401013355_AdicionandoTabelaOcorrencias")]
    partial class AdicionandoTabelaOcorrencias
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("apiweb.Entity.OcorrenciaEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("dataOcorrencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("detalhes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("usuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("usuarioId");

                    b.ToTable("Ocorrencias");
                });

            modelBuilder.Entity("apiweb.Entity.UsuarioEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("idade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("apiweb.Entity.OcorrenciaEntity", b =>
                {
                    b.HasOne("apiweb.Entity.UsuarioEntity", "usuario")
                        .WithMany("ocorrencias")
                        .HasForeignKey("usuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("apiweb.Entity.UsuarioEntity", b =>
                {
                    b.Navigation("ocorrencias");
                });
#pragma warning restore 612, 618
        }
    }
}
